AWS_ACCESS_KEY="YOUR_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY="YOUR_SECRET_ACCESS_KEY"
AWS_DEFAULT_REGION="YOUR_DEFAULT_REGION"
LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"


export LD_PRELOAD AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION

